# Generated by Django 5.0.6 on 2024-08-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='features_opisanie_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='features_opisanie_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='features_opisanie_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='features_opisanie_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='features_opisanie_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='features_opisanie_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
