# Generated by Django 5.0.6 on 2024-07-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_banner',
            new_name='about_banner_title',
        ),
        migrations.AddField(
            model_name='about',
            name='about_opisanie_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='about_opisanie_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='about_opisanie_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='about_zaglavtext',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
