# Generated by Django 5.0.6 on 2024-07-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_about_picture_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_opisanie_4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
