# Generated by Django 5.0.6 on 2024-07-05 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_products_picture_1'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='products_opisanie_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='products_opisanie_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='products_opisanie_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='products_opisanie_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='products_picture_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_picture_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_picture_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
