# Generated by Django 5.0.6 on 2024-08-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_photopage_alter_products_products_picture_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoPage',
        ),
    ]
