# Generated by Django 5.0.6 on 2024-07-05 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('store_zagolovok', models.CharField(blank=True, max_length=100, null=True)),
                ('store_podzagolovok', models.CharField(blank=True, max_length=100, null=True)),
                ('store_opisanie_1', models.CharField(blank=True, max_length=100, null=True)),
                ('store_opisanie_2', models.CharField(blank=True, max_length=100, null=True)),
                ('store_opisanie_3', models.CharField(blank=True, max_length=100, null=True)),
                ('store_opisanie_4', models.CharField(blank=True, max_length=100, null=True)),
                ('store_opisanie_5', models.CharField(blank=True, max_length=100, null=True)),
                ('store_opisanie_6', models.CharField(blank=True, max_length=100, null=True)),
                ('store_pic_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('store_pic_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('store_pic_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
